# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'helloWorldImg'

steps:
- script: 
    echo ====================;
    pwd;
    echo ====================;
    cd /home/vsts/work/1/s/my-app;
    mvn package;
    java -cp target/my-app-1.0-SNAPSHOT.jar com.mycompany.app.App;
  displayName: 'build'

- task: CopyFiles@2
  inputs:
    contents: '/home/vsts/work/1/s/my-app/target/**'
    targetFolder: $(Build.ArtifactStagingDirectory)

#- task: PublishBuildArtifacts@1
#  inputs:
#    pathToPublish: $(Build.ArtifactStagingDirectory)
#    artifactName: HelloWorld

- task: PublishPipelineArtifact@1
  inputs:
    #targetPath: '$(Pipeline.Workspace)' 
    targetPath: '/home/vsts/work/1/s/my-app/target/my-app-1.0-SNAPSHOT.jar'
    artifactName: 'HelloWorld'

#- task: Docker@2
#  displayName: Build an image
#  inputs:
#    repository: $(imageName)
#    command: build
#    Dockerfile: /home/vsts/work/1/s/my-app/Dockerfile