# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: 
    cd /home/vsts/work/1/s/my-app;
    mvn package;
    java -cp target/my-app-1.0-SNAPSHOT.jar com.mycompany.app.App;
  displayName: 'build'
